<?php
$a=array(
    'amir'=>array(
        'math'=>'95',
        'english'=>'94',
        'php'=>'93',
    ),
    'owais'=>array(
        'math'=>'90',
        'english'=>'99',
        'php'=>'98',
    )
);
print_r($a);
?>